# -*- coding: utf-8 -*-
"""Final Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGFCB-WK9CqoYa0B1GE3dwEc7MX4HG_N

# Dataset
"""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/"

!ls "/content/drive/MyDrive/codedex/"

!pip install plotly

#install streamlit and dash

#library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
plt.style.use("ggplot")
sns.set_palette("pastel")

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 1000)

base_path = "/content/drive/MyDrive/codedex/"

circuits = pd.read_csv(base_path + "circuits.csv")
constructor_results = pd.read_csv(base_path + "constructor_results.csv")
constructor_standings = pd.read_csv(base_path + "constructor_standings.csv")
constructors = pd.read_csv(base_path + "constructors.csv")
driver_standings = pd.read_csv(base_path + "driver_standings.csv")
drivers = pd.read_csv(base_path + "drivers.csv")
lap_times = pd.read_csv(base_path + "lap_times.csv")
pit_stops = pd.read_csv(base_path + "pit_stops.csv")
qualifying = pd.read_csv(base_path + "qualifying.csv")
races = pd.read_csv(base_path + "races.csv")
results = pd.read_csv(base_path + "results.csv")
seasons = pd.read_csv(base_path + "seasons.csv")
sprint_results = pd.read_csv(base_path + "sprint_results.csv")
status = pd.read_csv(base_path + "status.csv")

"""# Load Data

## Circuit
"""

file_path = "/content/drive/MyDrive/codedex/circuits.csv"

circuits = pd.read_csv(file_path)
circuits.head()

circuits.shape

"""## Races"""

file_path = "/content/drive/MyDrive/codedex/races.csv"

races = pd.read_csv(file_path)
races.head()

races.shape

"""## Qualifying"""

file_path = "/content/drive/MyDrive/codedex/qualifying.csv"

qualifying = pd.read_csv(file_path)
qualifying.head()

"""## Driver"""

file_path = "/content/drive/MyDrive/codedex/drivers.csv"

drivers = pd.read_csv(file_path)
drivers.head()

"""## Results"""

file_path = "/content/drive/MyDrive/codedex/results.csv"

results = pd.read_csv(file_path)
results.head()

"""## Lap times"""

file_path = "/content/drive/MyDrive/codedex/lap_times.csv"

lap_times = pd.read_csv(file_path)
lap_times.head()

"""## Pit stops"""

file_path = "/content/drive/MyDrive/codedex/pit_stops.csv"

pit_stops = pd.read_csv(file_path)
pit_stops.head()

"""# Data Exploration"""

# DATA EXPLORATION
print("\n DATA EXPLORATION")

# Check data structure
print("\n 1️ RACES DATA:")
print(races.head(3))
print(f"\nColumns: {races.columns.tolist()}")
print(f"Date range: {races['year'].min()} - {races['year'].max()}")

print("\n 2 QUALIFYING DATA:")
print(qualifying.head(3))
print(f"\nColumns: {qualifying.columns.tolist()}")

print("\n 3️ RESULTS DATA:")
print(results.head(3))
print(f"\nColumns: {results.columns.tolist()}")

print("\n 4️ CIRCUITS DATA:")
print(circuits.head(3))
print(f"\nColumns: {circuits.columns.tolist()}")

print("\nc5️ DRIVERS DATA:")
print(drivers.head(3))
print(f"\nColumns: {drivers.columns.tolist()}")

print("\n 6️ PIT STOPS DATA:")
print(pit_stops.head(3))

print(f"\nColumns: {pit_stops.columns.tolist()}")

print("\n 7️ LAP TIMES DATA:")
print(lap_times.head(3))
print(f"\nColumns: {lap_times.columns.tolist()}")

"""# Data Cleanning"""

# DATA QUALITY CHECK
print("\n DATA QUALITY CHECK")

# 1. Missing Values
print("\n MISSING VALUES CHECK:")
print("\nRACES:")
missing_races = races.isnull().sum()
print(missing_races[missing_races > 0] if missing_races.sum() > 0 else "No missing values")

print("\nQUALIFYING:")
missing_qual = qualifying.isnull().sum()
print(missing_qual[missing_qual > 0] if missing_qual.sum() > 0 else "No missing values")

print("\nRESULTS:")
missing_results = results.isnull().sum()
print(missing_results[missing_results > 0] if missing_results.sum() > 0 else "No missing values")

print("\nPIT STOPS:")
missing_pit = pit_stops.isnull().sum()
print(missing_pit[missing_pit > 0] if missing_pit.sum() > 0 else "No missing values")

print("\nLAP TIMES:")
missing_lap = lap_times.isnull().sum()
print(missing_lap[missing_lap > 0] if missing_lap.sum() > 0 else "No missing values")

# 2. Duplicates
print("DUPLICATE CHECK:")
print("\n" + "="*70)
print(f"Races: {races.duplicated().sum()} duplicates")
print(f"Qualifying: {qualifying.duplicated().sum()} duplicates")
print(f"Results: {results.duplicated().sum()} duplicates")
print(f"Pit Stops: {pit_stops.duplicated().sum()} duplicates")

# 3. Data Types
print("\n" + "="*70)
print("DATA TYPES CHECK:")
print("\nQUALIFYING 'position' type:", qualifying['position'].dtype)
print("RESULTS 'position' type:", results['position'].dtype)

# 4. Position Values
print("\n" + "="*70)
print("POSITION VALUES:")
print(f"\nQualifying - Missing positions: {qualifying['position'].isnull().sum()}")
print(f"Qualifying - Unique positions: {qualifying['position'].nunique()}")
print(f"Sample positions: {sorted(qualifying['position'].dropna().unique())[:10]}")

print(f"\nResults - Missing positions: {results['position'].isnull().sum()}")
print(f"Results - Unique positions: {results['position'].nunique()}")

# 5. Outliers Check
print("\n" + "="*70)
print("OUTLIERS CHECK:")

# Pit stops duration
if len(pit_stops) > 0:
    pit_stats = pit_stops['milliseconds'].describe()
    print("\nPit Stop Duration (milliseconds):")
    print(f"   Min: {pit_stats['min']:.0f} ms ({pit_stats['min']/1000:.2f}s)")
    print(f"   Max: {pit_stats['max']:.0f} ms ({pit_stats['max']/1000:.2f}s)")
    print(f"   Mean: {pit_stats['mean']:.0f} ms ({pit_stats['mean']/1000:.2f}s)")

    # Check for unrealistic values
    weird_pits = pit_stops[
        (pit_stops['milliseconds'] < 1000) |
        (pit_stops['milliseconds'] > 100000)
    ]
    print(f"Unrealistic pit stops (< 1s or > 100s): {len(weird_pits)}")

# Lap times
if len(lap_times) > 0:
    lap_stats = lap_times['milliseconds'].describe()
    print("\nLap Time Duration (milliseconds):")
    print(f"   Min: {lap_stats['min']:.0f} ms ({lap_stats['min']/1000:.2f}s)")
    print(f"   Max: {lap_stats['max']:.0f} ms ({lap_stats['max']/1000:.2f}s)")
    print(f"   Mean: {lap_stats['mean']:.0f} ms ({lap_stats['mean']/1000:.2f}s)")

    # Check for unrealistic values
    weird_laps = lap_times[
        (lap_times['milliseconds'] < 30000) |
        (lap_times['milliseconds'] > 300000)
    ]
    print(f"Unrealistic lap times (< 30s or > 5min): {len(weird_laps)}")

print("\n Quality check complete!")

# DATA CLEANING

print("\n DATA CLEANING")
print("="*70)

# 1. QUALIFYING - Remove rows without position and convert to int
qualifying_clean = qualifying.dropna(subset=['position']).copy()
qualifying_clean['position'] = qualifying_clean['position'].astype(int)
print(f" Qualifying: {len(qualifying):,} → {len(qualifying_clean):,} rows (removed {len(qualifying) - len(qualifying_clean):,} rows with missing position)")

# 2. RESULTS - Handle position column
results_clean = results.copy()

# Convert position to numeric (handles '\\N' strings)
results_clean['position'] = pd.to_numeric(results_clean['position'], errors='coerce')

# Use positionOrder as backup (more reliable)
if 'positionOrder' in results_clean.columns:
    results_clean['positionOrder'] = pd.to_numeric(results_clean['positionOrder'], errors='coerce')
    print(f" Results: {len(results):,} rows (using positionOrder for reliability)")
else:
    print(f" Results: {len(results):,} rows")

# 3. PIT STOPS - Filter realistic durations
pit_stops_clean = pit_stops[
    (pit_stops['milliseconds'] > 0) &      # Positive
    (pit_stops['milliseconds'] < 100000)   # Less than 100 seconds
].copy()
removed_pits = len(pit_stops) - len(pit_stops_clean)
print(f" Pit Stops: {len(pit_stops):,} → {len(pit_stops_clean):,} rows (removed {removed_pits:,} outliers)")

# 4. LAP TIMES - Filter realistic times
lap_times_clean = lap_times[
    (lap_times['milliseconds'] > 30000) &   # More than 30 seconds
    (lap_times['milliseconds'] < 300000)    # Less than 5 minutes
].copy()
removed_laps = len(lap_times) - len(lap_times_clean)
print(f" Lap Times: {len(lap_times):,} → {len(lap_times_clean):,} rows (removed {removed_laps:,} outliers)")

# 5. RACES, CIRCUITS, DRIVERS - Usually clean
races_clean = races.dropna(subset=['circuitId']).copy()
circuits_clean = circuits.copy()
drivers_clean = drivers.copy()

print(f" Races: {len(races_clean):,} rows")
print(f" Circuits: {len(circuits_clean):,} rows")
print(f" Drivers: {len(drivers_clean):,} rows")

# 6. Filter to Modern F1 Era (2010-2024)
print("\n" + "="*70)
print("FILTERING TO MODERN ERA (2010-2024):")

recent_races = races_clean[races_clean['year'] >= 2010].copy()
recent_race_ids = recent_races['raceId'].unique()

qualifying_recent = qualifying_clean[qualifying_clean['raceId'].isin(recent_race_ids)].copy()
results_recent = results_clean[results_clean['raceId'].isin(recent_race_ids)].copy()
pit_stops_recent = pit_stops_clean[pit_stops_clean['raceId'].isin(recent_race_ids)].copy()
lap_times_recent = lap_times_clean[lap_times_clean['raceId'].isin(recent_race_ids)].copy()  # ← FIXED LINE

print(f"   • Races: {len(recent_races):,}")
print(f"   • Qualifying: {len(qualifying_recent):,}")
print(f"   • Results: {len(results_recent):,}")
print(f"   • Pit Stops: {len(pit_stops_recent):,}")
print(f"   • Lap Times: {len(lap_times_recent):,}")
print(f"   • Years: {sorted(recent_races['year'].unique())}")

print("\n DATA CLEANING COMPLETE!")

"""# Data Analysis"""

# MAIN ANALYSIS - POLE POSITION WIN RATE

print("\n MAIN ANALYSIS: POLE POSITION WIN RATE")

# Step 1: Merge races with circuits
races_circuits = recent_races.merge(
    circuits_clean[['circuitId', 'name', 'location', 'country']],
    on='circuitId',
    suffixes=('_race', '_circuit')
)

# Step 2: Get pole positions (position = 1 in qualifying)
pole_positions = qualifying_recent[qualifying_recent['position'] == 1][['raceId', 'driverId']].copy()
pole_positions.columns = ['raceId', 'driverId_pole']

print(f" Found {len(pole_positions):,} pole positions")

# Step 3: Get race winners (position = 1 in results)
race_winners = results_recent[results_recent['position'] == 1][['raceId', 'driverId']].copy()
race_winners.columns = ['raceId', 'driverId_winner']

print(f" Found {len(race_winners):,} race winners")

# Step 4: Merge everything together
final_data = races_circuits.merge(pole_positions, on='raceId', how='left')
final_data = final_data.merge(race_winners, on='raceId', how='left')

# Step 5: Add driver names for pole position
final_data = final_data.merge(
    drivers_clean[['driverId', 'forename', 'surname']],
    left_on='driverId_pole',
    right_on='driverId',
    how='left'
)
final_data['pole_driver'] = final_data['forename'] + ' ' + final_data['surname']
final_data = final_data.drop(['driverId', 'forename', 'surname'], axis=1)

# Step 6: Add driver names for winner
final_data = final_data.merge(
    drivers_clean[['driverId', 'forename', 'surname']],
    left_on='driverId_winner',
    right_on='driverId',
    how='left'
)
final_data['winner_driver'] = final_data['forename'] + ' ' + final_data['surname']
final_data = final_data.drop(['driverId', 'forename', 'surname'], axis=1)

# Step 7: Check if pole position won
final_data['pole_wins'] = final_data['driverId_pole'] == final_data['driverId_winner']

# Remove rows where we don't have both pole and winner data
final_data_complete = final_data.dropna(subset=['driverId_pole', 'driverId_winner']).copy()

print(f" Analysis dataset: {len(final_data_complete):,} races with complete data")

# Calculate overall statistics
overall_win_rate = final_data_complete['pole_wins'].mean() * 100
total_races = len(final_data_complete)
pole_wins_count = final_data_complete['pole_wins'].sum()
non_pole_wins = total_races - pole_wins_count

print("\n" + "="*70)
print(" OVERALL STATISTICS (2010-2024)")
print("="*70)
print(f"Total races analyzed: {total_races:,}")
print(f"Pole position wins: {pole_wins_count:,}")
print(f"Non-pole wins: {non_pole_wins:,}")
print(f"\n Pole Position WIN RATE: {overall_win_rate:.1f}%")
print(f" Non-Pole WIN RATE: {100-overall_win_rate:.1f}%")
print("\n KEY INSIGHT:")
print(f"   '{100-overall_win_rate:.1f}% of races are won by drivers")
print(f"    who did NOT start from pole position!'")
print("="*70)

# Show sample data
print("\n Sample Data (First 10 races):")
print(final_data_complete[['year', 'name_race', 'name_circuit', 'pole_driver', 'winner_driver', 'pole_wins']].head(10))

# CIRCUIT-BY-CIRCUIT ANALYSIS
print("\n CIRCUIT-BY-CIRCUIT ANALYSIS")
print("="*70)

# Group by circuit
circuit_stats = final_data_complete.groupby('name_circuit').agg({
    'pole_wins': ['sum', 'count', 'mean']
}).reset_index()

circuit_stats.columns = ['circuit', 'wins_from_pole', 'total_races', 'win_rate']
circuit_stats['win_rate_pct'] = circuit_stats['win_rate'] * 100

# Filter: minimum 5 races for statistical significance
circuit_stats = circuit_stats[circuit_stats['total_races'] >= 5].copy()

# Sort by win rate (highest to lowest)
circuit_stats = circuit_stats.sort_values('win_rate_pct', ascending=False).reset_index(drop=True)

print(f"\n POLE POSITION WIN RATE BY CIRCUIT (Minimum 5 races):")
print("="*70)
print(circuit_stats[['circuit', 'total_races', 'wins_from_pole', 'win_rate_pct']].to_string(index=False))

# Identify extremes
print("\n" + "="*70)
print(" TOP 5 CIRCUITS (Pole Position Matters Most):")
print("="*70)
top_5 = circuit_stats.head(5)
for idx, row in top_5.iterrows():
    print(f"{idx+1}. {row['circuit']}: {row['win_rate_pct']:.1f}% ({int(row['wins_from_pole'])}/{int(row['total_races'])} races)")

print("\n" + "="*70)
print(" BOTTOM 5 CIRCUITS (Strategy Matters More):")
print("="*70)
bottom_5 = circuit_stats.tail(5)
for idx, row in bottom_5.iterrows():
    rank = len(circuit_stats) - list(bottom_5.index).index(idx)
    print(f"{rank}. {row['circuit']}: {row['win_rate_pct']:.1f}% ({int(row['wins_from_pole'])}/{int(row['total_races'])} races)")

# Save for later use
circuit_stats_final = circuit_stats.copy()

# PIT STOP ANALYSIS - "1 SECOND MATTERS"

print("\n PIT STOP ANALYSIS")
print("="*70)

# Average pit stop duration by year
pit_stop_by_year = pit_stops_recent.merge(
    recent_races[['raceId', 'year']],
    on='raceId'
).groupby('year')['milliseconds'].agg(['mean', 'median', 'min', 'max', 'count']).reset_index()

pit_stop_by_year['mean_seconds'] = pit_stop_by_year['mean'] / 1000
pit_stop_by_year['median_seconds'] = pit_stop_by_year['median'] / 1000
pit_stop_by_year['min_seconds'] = pit_stop_by_year['min'] / 1000
pit_stop_by_year['max_seconds'] = pit_stop_by_year['max'] / 1000

print("\n AVERAGE PIT STOP DURATION BY YEAR:")
print(pit_stop_by_year[['year', 'mean_seconds', 'median_seconds', 'count']].to_string(index=False))

# Fastest pit stops ever
fastest_stops = pit_stops_recent.nsmallest(10, 'milliseconds').copy()
fastest_stops = fastest_stops.merge(recent_races[['raceId', 'year', 'name']], on='raceId')
fastest_stops = fastest_stops.merge(drivers_clean[['driverId', 'forename', 'surname']], on='driverId')
fastest_stops['driver_name'] = fastest_stops['forename'] + ' ' + fastest_stops['surname']
fastest_stops['duration_sec'] = fastest_stops['milliseconds'] / 1000

print("\n" + "="*70)
print("TOP 10 FASTEST PIT STOPS (2010-2024):")
print("="*70)
print(fastest_stops[['year', 'name', 'driver_name', 'stop', 'duration_sec']].to_string(index=False))

# Improvement
if len(pit_stop_by_year) > 1:
    earliest_year = pit_stop_by_year.iloc[0]
    latest_year = pit_stop_by_year.iloc[-1]
    improvement = earliest_year['mean_seconds'] - latest_year['mean_seconds']
    improvement_pct = (improvement / earliest_year['mean_seconds']) * 100

    print("\n" + "="*70)
    print(" PIT STOP EVOLUTION:")
    print("="*70)
    print(f"   {int(earliest_year['year'])}: {earliest_year['mean_seconds']:.2f}s average")
    print(f"   {int(latest_year['year'])}: {latest_year['mean_seconds']:.2f}s average")
    print(f"   Improvement: {improvement:.2f}s ({improvement_pct:.1f}% faster)")
    print("\n INSIGHT: Teams are getting faster every year!")

# COMEBACK VICTORIES ANALYSIS

print("\n COMEBACK VICTORIES ANALYSIS")
print("="*70)

# Merge qualifying starting positions with race results
comeback_data = results_recent.merge(
    qualifying_recent[['raceId', 'driverId', 'position']],
    on=['raceId', 'driverId'],
    suffixes=('_finish', '_start'),
    how='left'
)

# Filter: Winners (position_finish = 1) who did NOT start from pole (position_start > 1)
comeback_wins = comeback_data[
    (comeback_data['position_finish'] == 1) &
    (comeback_data['position_start'] > 1) &
    (comeback_data['position_start'].notna())
].copy()

# Add race and driver info
comeback_wins = comeback_wins.merge(recent_races[['raceId', 'year', 'name']], on='raceId')
comeback_wins = comeback_wins.merge(drivers_clean[['driverId', 'forename', 'surname']], on='driverId')
comeback_wins['driver_name'] = comeback_wins['forename'] + ' ' + comeback_wins['surname']

# Sort by starting position (biggest comebacks first)
comeback_wins = comeback_wins.sort_values('position_start', ascending=False)

print(f"\n COMEBACK VICTORIES (Won from NON-pole, 2010-2024):")
print(f"Total: {len(comeback_wins):,} races")
print("\n" + "="*70)
print(" TOP 10 BIGGEST COMEBACKS:")
print("="*70)
print(comeback_wins[['year', 'name', 'driver_name', 'position_start']].head(10).to_string(index=False))

# Stats by starting position
if len(comeback_wins) > 0:
    comeback_by_pos = comeback_wins.groupby('position_start').size().reset_index(name='wins')
    comeback_by_pos = comeback_by_pos.sort_values('position_start')

    print("\n" + "="*70)
    print(" WINS BY STARTING POSITION (Non-pole):")
    print("="*70)
    for idx, row in comeback_by_pos.head(10).iterrows():
        print(f"   P{int(row['position_start'])}: {row['wins']} wins")

# VISUALIZATION 1 - MAIN BAR CHART (Circuit Win Rate)
# Visualization 1: Circuit-by-Circuit Pole Win Rate
plt.figure(figsize=(14, 10))
cmap = plt.get_cmap("viridis")
colors = cmap(np.linspace(0.2, 0.9, len(circuit_stats_final)))
bars = plt.barh(circuit_stats_final['circuit'], circuit_stats_final['win_rate_pct'], color=colors, edgecolor='black', linewidth=0.5)
for i, (circuit, rate) in enumerate(zip(circuit_stats_final['circuit'], circuit_stats_final['win_rate_pct'])):
    plt.text(rate + 1.5, i, f'{rate:.1f}%', va='center', fontsize=9, fontweight='bold')
plt.xlabel('Pole Position Win Rate (%)', fontsize=13, fontweight='bold')
plt.ylabel('Circuit', fontsize=13, fontweight='bold')
plt.title('Pole Position Win Rate by Circuit (2010-2024)\n"Starting First Doesn\'t Always Mean Winning"',
          fontsize=16, fontweight='bold', pad=20)
plt.xlim(0, 100)
plt.axvline(overall_win_rate, color='blue', linestyle='--', linewidth=2.5, alpha=0.7,
            label=f'Overall Average: {overall_win_rate:.1f}%')
plt.legend(fontsize=11, loc='lower right')
plt.grid(axis='x', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('1_circuit_pole_winrate.png', dpi=300, bbox_inches='tight')
plt.show()

# VISUALIZATION 2 - TOP vs BOTTOM CIRCUITS
# Top 5 vs Bottom 5 Comparison
top_5_circuits = circuit_stats_final.head(5)
bottom_5_circuits = circuit_stats_final.tail(5)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# LEFT: Top 5 (Green theme - Pole Dominates)
ax1.barh(top_5_circuits['circuit'], top_5_circuits['win_rate_pct'],
         color='darkblue', alpha=0.8, edgecolor='black', linewidth=1)
for i, (circuit, rate) in enumerate(zip(top_5_circuits['circuit'], top_5_circuits['win_rate_pct'])):
    ax1.text(rate + 2, i, f'{rate:.1f}%', va='center', fontweight='bold', fontsize=11)
ax1.set_xlabel('Win Rate (%)', fontweight='bold', fontsize=12)
ax1.set_title('TOP 5: Pole Position = Huge Advantage\n(Hard to Overtake)',
              fontsize=13, fontweight='bold', color='darkblue', pad=15)
ax1.set_xlim(0, 100)
ax1.invert_yaxis()
ax1.grid(axis='x', alpha=0.3, linestyle='--')

# RIGHT: Bottom 5 (Red theme - Strategy Matters)
ax2.barh(bottom_5_circuits['circuit'], bottom_5_circuits['win_rate_pct'],
         color='skyblue', alpha=0.8, edgecolor='black', linewidth=1)
for i, (circuit, rate) in enumerate(zip(bottom_5_circuits['circuit'], bottom_5_circuits['win_rate_pct'])):
    ax2.text(rate + 2, i, f'{rate:.1f}%', va='center', fontweight='bold', fontsize=11)
ax2.set_xlabel('Win Rate (%)', fontweight='bold', fontsize=12)
ax2.set_title('BOTTOM 5: Strategy > Starting Position\n(Overtaking Possible)',
              fontsize=13, fontweight='bold', color='skyblue', pad=15)
ax2.set_xlim(0, 100)
ax2.invert_yaxis()
ax2.grid(axis='x', alpha=0.3, linestyle='--')
plt.suptitle('Circuit Comparison: Where Does Pole Position Matter?',
             fontsize=15, fontweight='bold', y=1.02)
plt.style.use('seaborn-v0_8-whitegrid')
plt.tight_layout()
plt.savefig('2_top_bottom_circuits.png', dpi=300, bbox_inches='tight')
plt.show()

# SECTION 12: VISUALIZATION 3 - PIT STOP EVOLUTION
# Visualization 3: Pit Stop Evolution Over Time
plt.figure(figsize=(13, 7))
plt.plot(pit_stop_by_year['year'], pit_stop_by_year['mean_seconds'],
         marker='o', linewidth=3, markersize=10, color='darkblue', label='Average Pit Stop')
plt.fill_between(pit_stop_by_year['year'], pit_stop_by_year['mean_seconds'],
                 alpha=0.3, color='skyblue')
plt.xlabel('Year', fontsize=13, fontweight='bold')
plt.ylabel('Average Pit Stop Duration (seconds)', fontsize=13, fontweight='bold')
plt.title('Pit Stop Evolution: Every Millisecond Matters\n"1 Second Can Change Everything" (2010-2024)',
          fontsize=15, fontweight='bold', pad=20)
plt.grid(True, alpha=0.4, linestyle='--')
fastest_year_idx = pit_stop_by_year['mean_seconds'].idxmin()
fastest_year_data = pit_stop_by_year.loc[fastest_year_idx]
plt.annotate(f'Fastest: {fastest_year_data["mean_seconds"]:.2f}s\n({int(fastest_year_data["year"])})',
             xy=(fastest_year_data['year'], fastest_year_data['mean_seconds']),
             xytext=(fastest_year_data['year']+1.5, fastest_year_data['mean_seconds']+0.5),
             arrowprops=dict(arrowstyle='->', color='red', lw=2.5),
             fontsize=11, fontweight='bold', color='red',
             bbox=dict(boxstyle='round,pad=0.5', facecolor='yellow', alpha=0.7))
if len(pit_stop_by_year) > 1:
    start_year = pit_stop_by_year.iloc[0]
    end_year = pit_stop_by_year.iloc[-1]
    plt.annotate(f'{improvement:.2f}s faster\n({improvement_pct:.1f}% improvement)',
                 xy=(end_year['year'], end_year['mean_seconds']),
                 xytext=(end_year['year']-3, end_year['mean_seconds']+1),
                 arrowprops=dict(arrowstyle='->', color='green', lw=2),
                 fontsize=10, fontweight='bold', color='green',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor='lightgreen', alpha=0.7))
plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('3_pit_stop_evolution.png', dpi=300, bbox_inches='tight')
plt.show()

from matplotlib.ticker import MultipleLocator

#  PIT STOP EVOLUTION
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(13, 7))
plt.plot(
    pit_stop_by_year['year'],
    pit_stop_by_year['mean_seconds'],
    marker='o',
    linewidth=3,
    markersize=9,
    color='darkblue',
    label='Average Pit Stop'
)
# Area Fill
plt.fill_between(
    pit_stop_by_year['year'],
    pit_stop_by_year['mean_seconds'],
    alpha=0.25,
    color='skyblue'
)
# Labels & Title
plt.xlabel('Year', fontsize=13, fontweight='bold')
plt.ylabel('Average Pit Stop Duration (seconds)', fontsize=13, fontweight='bold')
plt.title(
    'Pit Stop Evolution: Every Millisecond Matters\n"1 Second Can Change Everything" (2010-2024)',
    fontsize=15,
    fontweight='bold',
    pad=20
)

plt.grid(True, alpha=0.3, linestyle='--')
y_min = np.floor(pit_stop_by_year['mean_seconds'].min())
y_max = np.ceil(pit_stop_by_year['mean_seconds'].max())
plt.ylim(y_min - 0.5, y_max + 0.5)
plt.gca().yaxis.set_major_locator(MultipleLocator(1))
fastest_year_idx = pit_stop_by_year['mean_seconds'].idxmin()
fastest_year_data = pit_stop_by_year.loc[fastest_year_idx]

plt.annotate(
    f'Fastest: {fastest_year_data["mean_seconds"]:.2f}s\n({int(fastest_year_data["year"])})',
    xy=(fastest_year_data['year'], fastest_year_data['mean_seconds']),
    xytext=(fastest_year_data['year'] + 1.5,
            fastest_year_data['mean_seconds'] + 0.5),
    arrowprops=dict(arrowstyle='->', color='red', lw=2),
    fontsize=11,
    fontweight='bold',
    color='red',
    bbox=dict(boxstyle='round,pad=0.5', facecolor='yellow', alpha=0.7)
)

if len(pit_stop_by_year) > 1:

    start_year = pit_stop_by_year.iloc[0]
    end_year = pit_stop_by_year.iloc[-1]

    improvement = start_year['mean_seconds'] - end_year['mean_seconds']
    improvement_pct = (improvement / start_year['mean_seconds']) * 100

    plt.annotate(
        f'{improvement:.2f}s faster\n({improvement_pct:.1f}% improvement)',
        xy=(end_year['year'], end_year['mean_seconds']),
        xytext=(end_year['year'] - 3,
                end_year['mean_seconds'] + 1),
        arrowprops=dict(arrowstyle='->', color='green', lw=2),
        fontsize=10,
        fontweight='bold',
        color='green',
        bbox=dict(boxstyle='round,pad=0.5', facecolor='lightgreen', alpha=0.7)
    )

plt.legend(fontsize=11)
plt.tight_layout()
plt.savefig('3_pit_stop_evolution.png', dpi=300, bbox_inches='tight')
plt.show()

# VISUALIZATION 4 - OVERALL SUMMARY
# Visualization 4: Overall Win Rate Pie Chart
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))

# LEFT: Pie Chart - Overall Win Distribution
sizes = [pole_wins_count, non_pole_wins]
labels = [f'Pole Position Wins\n{overall_win_rate:.1f}%',
          f'Non-Pole Wins\n{100-overall_win_rate:.1f}%']
colors_pie = ['#2874A6', '#7B7D7D']
explode = (0.05, 0.05)
wedges, texts, autotexts = ax1.pie(sizes, labels=labels, autopct='%1.0f%%',
                                     colors=colors_pie, explode=explode,
                                     shadow=True, startangle=90,
                                     textprops={'fontsize': 12, 'fontweight': 'bold'})
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(14)
    autotext.set_fontweight('bold')

ax1.set_title('Overall Race Wins Distribution\n(2010-2024)',
              fontsize=14, fontweight='bold', pad=20)

# RIGHT: Bar Chart - Win Count
categories = ['Pole Position', 'Non-Pole']
values = [pole_wins_count, non_pole_wins]
colors_bar = ['#2874A6', '#7B7D7D']
bars = ax2.bar(categories, values, color=colors_bar, alpha=0.8, edgecolor='black', linewidth=2)
for bar, val in zip(bars, values):
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(val)} races',
             ha='center', va='bottom', fontsize=13, fontweight='bold')
ax2.set_ylabel('Number of Wins', fontsize=13, fontweight='bold')
ax2.set_title(f'Total Wins Comparison\n(out of {total_races} races)',
              fontsize=14, fontweight='bold', pad=20)
ax2.grid(axis='y', alpha=0.3, linestyle='--')
plt.style.use('seaborn-v0_8-whitegrid')
plt.suptitle(f'F1 Analysis Summary: "Starting First ≠ Winning" ({recent_races["year"].min()}-{recent_races["year"].max()})',
             fontsize=16, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('4_overall_summary.png', dpi=300, bbox_inches='tight')
plt.show()



"""# Interactive Dashboard"""

# INTERACTIVE F1 DASHBOARD
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# CHART 1: Interactive Bar Chart - Circuit Win Rate
# Prepare data
circuit_stats_sorted = circuit_stats_final.sort_values('win_rate_pct', ascending=True)

colors_plotly = []
for rate in circuit_stats_sorted['win_rate_pct']:
    if rate >= 60:
        colors_plotly.append('#1B4F72')  # Navy - high dominance
    elif rate >= 45:
        colors_plotly.append('#2E86C1')  # Medium Blue
    else:
        colors_plotly.append('#7B7D7D')  # Grey - more strategic

fig1 = go.Figure()

fig1.add_trace(go.Bar(
    y=circuit_stats_sorted['circuit'],
    x=circuit_stats_sorted['win_rate_pct'],
    orientation='h',
    marker=dict(
        color=colors_plotly,
        line=dict(color='black', width=1)
    ),
    text=circuit_stats_sorted['win_rate_pct'].round(1).astype(str) + '%',
    textposition='outside',
    hovertemplate='<b>%{y}</b><br>' +
                  'Win Rate: %{x:.1f}%<br>' +
                  'Total Races: %{customdata[0]}<br>' +
                  'Wins from Pole: %{customdata[1]}<br>' +
                  '<extra></extra>',
    customdata=circuit_stats_sorted[['total_races', 'wins_from_pole']].values
))

# Add average line
fig1.add_vline(
    x=overall_win_rate,
    line_dash="dash",
    line_color="blue",
    line_width=3,
    annotation_text=f"Average: {overall_win_rate:.1f}%",
    annotation_position="top right"
)

fig1.update_layout(
    title={
        'text': 'Pole Position Win Rate by Circuit (2010-2024)<br><sub>Interactive: Hover for details</sub>',
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 20, 'family': 'Arial Black'}
    },
    xaxis_title='Win Rate (%)',
    yaxis_title='Circuit',
    height=800,
    width=1200,
    template='plotly_white',
    font=dict(size=11),
    xaxis=dict(range=[0, 100]),
    showlegend=False
)

# Save as HTML
fig1.write_html('dashboard_1_circuit_winrate.html')
print(" Saved: dashboard_1_circuit_winrate.html")

# Show in notebook
fig1.show()

# CHART 2: Interactive Line Chart - Pit Stop Evolution

fig2 = go.Figure()
fig2.add_trace(go.Scatter(
    x=pit_stop_by_year['year'],
    y=pit_stop_by_year['mean_seconds'],
    mode='lines+markers',
    name='Average Pit Stop',
    line=dict(color='dark blue', width=4),
    marker=dict(size=12, symbol='circle', line=dict(width=2, color='black')),
    fill='tozeroy',
    fillcolor='rgba(30, 86, 160, 0.2)',
    hovertemplate='<b>Year: %{x}</b><br>' +
                  'Avg Duration: %{y:.2f}s<br>' +
                  'Total Stops: %{customdata[0]:,}<br>' +
                  '<extra></extra>',
    customdata=pit_stop_by_year[['count']].values
))

# Annotate fastest year
fastest_idx = pit_stop_by_year['mean_seconds'].idxmin()
fastest_data = pit_stop_by_year.loc[fastest_idx]

fig2.add_annotation(
    x=fastest_data['year'],
    y=fastest_data['mean_seconds'],
    text=f"Fastest: {fastest_data['mean_seconds']:.2f}s<br>({int(fastest_data['year'])})",
    showarrow=True,
    arrowhead=2,
    arrowsize=1,
    arrowwidth=2,
    arrowcolor='#1E56A0',
    ax=40,
    ay=-40,
    bgcolor='rgba(30, 86, 160, 0.1)',
    bordercolor='#1E56A0',
    borderwidth=1.5,
    font=dict(size=12, color='#1E56A0', family='Arial')
)

fig2.update_layout(
    title={
        'text': 'Pit Stop Evolution: Every Millisecond Matters (2010-2024)<br><sub>Interactive: Hover for yearly stats</sub>',
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 18, 'family': 'Arial Black'}
    },
    xaxis_title='Year',
    yaxis_title='Average Pit Stop Duration (seconds)',
    height=600,
    width=1200,
    template='plotly_white',
    hovermode='x unified'
)

fig2.write_html('dashboard_2_pitstop_evolution.html')
fig2.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# ==========================
# PREPARE DATA
# ==========================

df = pit_stop_by_year.copy()

fastest_idx = df['mean_seconds'].idxmin()
fastest_data = df.loc[fastest_idx]

start_year = df.iloc[0]
end_year = df.iloc[-1]

improvement = start_year['mean_seconds'] - end_year['mean_seconds']
improvement_pct = (improvement / start_year['mean_seconds']) * 100

# ==========================
# CREATE DASHBOARD LAYOUT
# ==========================

fig = make_subplots(
    rows=2, cols=3,
    specs=[[{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}],
           [{"colspan": 3}, None, None]],
    vertical_spacing=0.15
)

# ==========================
# KPI 1 - Fastest Pit Stop
# ==========================

fig.add_trace(go.Indicator(
    mode="number",
    value=fastest_data['mean_seconds'],
    number={'suffix': " s"},
    title={"text": f"Fastest Pit Stop<br>{int(fastest_data['year'])}"},
), row=1, col=1)

# ==========================
# KPI 2 - Total Improvement
# ==========================

fig.add_trace(go.Indicator(
    mode="number+delta",
    value=end_year['mean_seconds'],
    delta={'reference': start_year['mean_seconds'], 'relative': True, 'valueformat': '.1%'},
    title={"text": "Total Improvement Since 2010"},
), row=1, col=2)

# ==========================
# KPI 3 - Latest Value
# ==========================

fig.add_trace(go.Indicator(
    mode="number",
    value=end_year['mean_seconds'],
    number={'suffix': " s"},
    title={"text": f"Latest Avg ({int(end_year['year'])})"},
), row=1, col=3)

# ==========================
# MAIN LINE CHART
# ==========================

fig.add_trace(go.Scatter(
    x=df['year'],
    y=df['mean_seconds'],
    mode='lines+markers',
    line=dict(color='#1E56A0', width=4),
    marker=dict(size=10),
    fill='tozeroy',
    fillcolor='rgba(30,86,160,0.15)',
    hovertemplate='<b>Year: %{x}</b><br>' +
                  'Avg Duration: %{y:.2f}s<br>' +
                  'Total Stops: %{customdata[0]:,}<br>' +
                  '<extra></extra>',
    customdata=df[['count']].values,
    name='Average Pit Stop'
), row=2, col=1)

# Fastest Annotation
fig.add_annotation(
    x=fastest_data['year'],
    y=fastest_data['mean_seconds'],
    text=f"Fastest: {fastest_data['mean_seconds']:.2f}s<br>({int(fastest_data['year'])})",
    showarrow=True,
    arrowhead=2,
    arrowcolor='#1E56A0',
    row=2,
    col=1
)

# ==========================
# LAYOUT STYLING
# ==========================

fig.update_layout(
    title={
        'text': '🏎️ Pit Stop Evolution Dashboard (2010–2024)<br><sup>Every Millisecond Matters</sup>',
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 22}
    },
    template='plotly_white',
    height=750,
    width=1300,
    hovermode='x unified',
    showlegend=False
)

fig.update_xaxes(title_text="Year", row=2, col=1)
fig.update_yaxes(title_text="Average Pit Stop Duration (seconds)", row=2, col=1)

fig.write_html("interactive_pitstop_dashboard.html")
fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# ==========================
# DATA PREP
# ==========================
df = pit_stop_by_year.copy()

fastest_idx = df['mean_seconds'].idxmin()
fastest_data = df.loc[fastest_idx]

start_year = df.iloc[0]
end_year = df.iloc[-1]

improvement = start_year['mean_seconds'] - end_year['mean_seconds']
improvement_pct = (improvement / start_year['mean_seconds']) * 100

# ==========================
# DASHBOARD LAYOUT
# ==========================
fig = make_subplots(
    rows=2, cols=3,
    specs=[[{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}],
           [{"colspan": 3}, None, None]],
    vertical_spacing=0.15
)

# ==========================
# KPI 1: Fastest Pit Stop
# ==========================
fig.add_trace(go.Indicator(
    mode="number",
    value=fastest_data['mean_seconds'],
    number={'suffix': " s", 'valueformat': ".2f"},
    title={"text": f"Fastest Pit Stop<br>{int(fastest_data['year'])}"}
), row=1, col=1)

# ==========================
# KPI 2: Total Improvement
# ==========================
fig.add_trace(go.Indicator(
    mode="number+delta",
    value=end_year['mean_seconds'],
    delta={'reference': start_year['mean_seconds'], 'relative': True, 'valueformat': '.1%'},
    number={'valueformat': ".2f"},
    title={"text": "Total Improvement Since 2010"}
), row=1, col=2)

# ==========================
# KPI 3: Latest Value
# ==========================
fig.add_trace(go.Indicator(
    mode="number",
    value=end_year['mean_seconds'],
    number={'suffix': " s", 'valueformat': ".2f"},
    title={"text": f"Latest Avg ({int(end_year['year'])})"}
), row=1, col=3)

# ==========================
# MAIN LINE CHART
# ==========================
fig.add_trace(go.Scatter(
    x=df['year'],
    y=df['mean_seconds'],
    mode='lines+markers',
    line=dict(color='#1E56A0', width=4),
    marker=dict(size=10, line=dict(width=2, color='black')),
    fill='tozeroy',
    fillcolor='rgba(30,86,160,0.15)',
    hovertemplate='<b>Year: %{x}</b><br>' +
                  'Avg Duration: %{y:.2f}s<br>' +
                  'Total Stops: %{customdata[0]:,}<br>' +
                  '<extra></extra>',
    customdata=df[['count']].values,
    name='Average Pit Stop'
), row=2, col=1)

# Fastest Year Annotation
fig.add_annotation(
    x=fastest_data['year'],
    y=fastest_data['mean_seconds'],
    text=f"Fastest: {fastest_data['mean_seconds']:.2f}s<br>({int(fastest_data['year'])})",
    showarrow=True,
    arrowhead=2,
    arrowsize=1,
    arrowwidth=2,
    arrowcolor='#1E56A0',
    ax=40,
    ay=-40,
    bgcolor='rgba(30,86,160,0.1)',
    bordercolor='#1E56A0',
    borderwidth=1.5,
    font=dict(size=12, color='#1E56A0', family='Arial')
)

# ==========================
# Y-AXIS SETTING (INTERVAL)
# ==========================
y_min = df['mean_seconds'].min() - 0.2
y_max = df['mean_seconds'].max() + 0.2

fig.update_yaxes(
    title_text="Average Pit Stop Duration (seconds)",
    range=[y_min, y_max],
    dtick=0.2,       # interval naik 0.2 detik
    tickformat=".2f",
    row=2, col=1
)

fig.update_xaxes(
    title_text="Year",
    row=2, col=1
)

# ==========================
# LAYOUT & STYLE
# ==========================
fig.update_layout(
    title={
        'text': '🏎️ Pit Stop Evolution Dashboard (2010–2024)<br><sup>Every Millisecond Matters</sup>',
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 22}
    },
    template='plotly_white',
    height=750,
    width=1300,
    hovermode='x unified',
    showlegend=False
)

# ==========================
# EXPORT
# ==========================
fig.write_html("interactive_pitstop_dashboard.html")
fig.show()

# CHART 3: Interactive Sunburst - Overall Summary

sunburst_data = pd.DataFrame({
    'labels': ['Total Races', 'Pole Wins', 'Non-Pole Wins'],
    'parents': ['', 'Total Races', 'Total Races'],
    'values': [total_races, pole_wins_count, non_pole_wins],
    'colors': ['#E5E7E9', '#1E56A0', '#5DADE2']
})

fig3 = go.Figure(go.Sunburst(
    labels=sunburst_data['labels'],
    parents=sunburst_data['parents'],
    values=sunburst_data['values'],
    marker=dict(
        colors=sunburst_data['colors'],
        line=dict(width=1.5, color='white')
    ),
    hovertemplate='<b>%{label}</b><br>' +
                  'Races: %{value:,}<br>' +
                  'Percentage: %{percentRoot:.1%}<br>' +
                  '<extra></extra>',
    textfont=dict(size=15, family='Arial')
))

fig3.update_layout(
    title={
        'text': f'F1 Race Wins Distribution (2010-2024)<br><sub>Total: {total_races:,} races</sub>',
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 20, 'family': 'Arial'}
    },
    height=600,
    width=800
)

fig3.write_html('dashboard_3_overall_summary.html')
fig3.show()

# Interactive Scatter - Circuit Characteristics

circuit_stats_final['category'] = circuit_stats_final['win_rate_pct'].apply(
    lambda x: 'Pole Dominates (60%+)' if x >= 60
    else 'Mixed (45-60%)' if x >= 45
    else 'Strategy Matters (<45%)'
)

fig4 = px.scatter(
    circuit_stats_final,
    x='total_races',
    y='win_rate_pct',
    size='wins_from_pole',
    color='category',
    hover_name='circuit',
    hover_data={
        'total_races': True,
        'wins_from_pole': True,
        'win_rate_pct': ':.1f',
        'category': False
    },
    labels={
        'total_races': 'Total Races',
        'win_rate_pct': 'Pole Win Rate (%)',
        'category': 'Circuit Type'
    },
    color_discrete_map={
        'Pole Dominates (60%+)': '#2E86C1',
        'Mixed (45-60%)': '#B9770E',
        'Strategy Matters (<45%)': '#7B7D7D'
    },
    title='Circuit Characteristics: Pole Importance vs Race Count<br><sub>Size = Wins from Pole</sub>'
)

fig4.update_layout(
    height=700,
    width=1200,
    template='plotly_white',
    title_x=0.5,
    title_font=dict(size=18, family='Arial Black')
)

fig4.add_hline(
    y=overall_win_rate,
    line_dash="dash",
    line_color="blue",
    annotation_text=f"Average: {overall_win_rate:.1f}%",
    annotation_position="right"
)

fig4.write_html('dashboard_4_circuit_scatter.html')
fig4.show()

# Combined Dashboard
from plotly.subplots import make_subplots

# Create 2x2 subplot
fig_combined = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Pole Win Rate by Circuit',
        'Pit Stop Evolution',
        'Overall Distribution',
        'Circuit Scatter'
    ),
    specs=[
        [{"type": "bar"}, {"type": "scatter"}],
        [{"type": "pie"}, {"type": "scatter"}]
    ],
    vertical_spacing=0.12,
    horizontal_spacing=0.10
)

# 1. Bar Chart (Top 10 circuits)
top_10 = circuit_stats_final.head(10).sort_values('win_rate_pct', ascending=True)
fig_combined.add_trace(
    go.Bar(
        y=top_10['circuit'],
        x=top_10['win_rate_pct'],
        orientation='h',
        marker=dict(color='#27ae60'),
        name='Win Rate',
        text=top_10['win_rate_pct'].round(1).astype(str) + '%',
        textposition='outside'
    ),
    row=1, col=1
)

# 2. Line Chart (Pit stops)
fig_combined.add_trace(
    go.Scatter(
        x=pit_stop_by_year['year'],
        y=pit_stop_by_year['mean_seconds'],
        mode='lines+markers',
        marker=dict(color='orangered', size=8),
        line=dict(color='orangered', width=3),
        name='Pit Stop'
    ),
    row=1, col=2
)

# 3. Pie Chart
fig_combined.add_trace(
    go.Pie(
        labels=['Pole Wins', 'Non-Pole Wins'],
        values=[pole_wins_count, non_pole_wins],
        marker=dict(colors=['#2ecc71', '#e74c3c']),
        hole=0.3,
        name='Distribution'
    ),
    row=2, col=1
)

# 4. Scatter
fig_combined.add_trace(
    go.Scatter(
        x=circuit_stats_final['total_races'],
        y=circuit_stats_final['win_rate_pct'],
        mode='markers',
        marker=dict(
            size=circuit_stats_final['wins_from_pole']*2,
            color=circuit_stats_final['win_rate_pct'],
            colorscale='RdYlGn',
            showscale=True,
            line=dict(width=1, color='black')
        ),
        text=circuit_stats_final['circuit'],
        name='Circuits'
    ),
    row=2, col=2
)

fig_combined.update_layout(
    title_text=f"F1 Interactive Dashboard: Pole Position Analysis (2010-2024)<br><sub>{total_races} races analyzed</sub>",
    title_x=0.5,
    title_font=dict(size=22, family='Arial Black'),
    height=1000,
    width=1600,
    showlegend=False,
    template='plotly_white'
)

fig_combined.update_xaxes(title_text="Win Rate (%)", row=1, col=1)
fig_combined.update_xaxes(title_text="Year", row=1, col=2)
fig_combined.update_xaxes(title_text="Total Races", row=2, col=2)
fig_combined.update_yaxes(title_text="Circuit", row=1, col=1)
fig_combined.update_yaxes(title_text="Duration (s)", row=1, col=2)
fig_combined.update_yaxes(title_text="Win Rate (%)", row=2, col=2)
fig_combined.write_html('dashboard_COMBINED.html')
fig_combined.show()